sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: D/Vx6RhaT+8hxwn/Dw9tmfRFCQW541GcZMCU3UBqy1d08CLMHgIlVd9VfilGrQxNreUr7lI6I7ez3vEJONupg0zj/hIjhl58BjGiMroFxpEzozLHbkVNB55q83RJTigXFwbabYE16Tn4DYBLBHeLDK89eVPhrbGKMYBOENZD2CbIPGWbdVnlqJ4lSpJ7VljvjR34yENXAjqopbsqWHf6eeyRd7VwqtO/NQbWgeZiRgQf6q16EkX6nWZKaCuLDxUBhjrrjayKEAmiveoTQsrZ9hnh285iWaIbYgmWyZ8y4JoL9Mx80026S5jpVCIxkzF6Ac2Vx2dkXV/o9LJUIK9AyAhq/WO4ARYVvzLDj/46qBYQzWMv/V7gM9n0+Z7ikHNiO/EJydyzHbcln8Z8Ptzb7fe6CVD9HoGy6TBT2rtrrU6sH5+rE9+VQ9XPV8h8/A0Y/4bF+1+E6J3H6rvBij0QqnhaF9hTAc3s/dtyAhyBhIyOOAdQJNdWwaVbHbn2MoQ0KowQIBgrZPnfg2xNh/R/7ifV7GF4Qb8+XLVTxTc66QqE5s1uajJDp773ZCRlaKeaHISx0lk8Awq+Lb93OaGNlIrAXvcFhd7EemqgOulKvAov01/B3bVaMu9kPnjbJWr6a9hXtf+7d6EjSBvN3WvEj6r4oSBhwNoLK0OkllM6TxM=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Two-Festivals_4056
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy